### PR TITLE
chore(version): Bumped to 0.0.1-alpha.20

### PR DESCRIPTION
**Pull request by zero0Halo**
**Before submitting a pull request,** please make sure the following is done:

I have done **all** of the following:

- [ ] Added a top level class to all my components `'.anchor-[COMPONENT NAME]'`.
- [ ] Used [conventional commits](https://www.conventionalcommits.org) for all work.
- [ ] Tested my solution on Mobile & Tablet.
- [ ] Wrote [unit tests](https://jestjs.io/docs/en/getting-started) for states and all behavior (`npm test`) and passed coverage thresholds.
- [ ] Updated snapshots for all permutations (`npm test -- -u`).
- [ ] Accounted for hover, focus, blur, visited, & error states because they are not edge cases.
- [ ] Created TODOs for known edge cases.
- [ ] Documented all of my changes (inline & doc site).
- [ ] Made sure that all accessibility errors are resolved.
- [ ] Added [stories](https://storybook.js.org/docs/basics/introduction/) with knobs for all possible configurations.
- [ ] De-linted and ran [prettier](https://github.com/prettier/prettier) (`npm run pretty`) on my code.

---------
**Outline your feature or bug-fix below**

My code does...

### CODE REVIEW

**Comment by zero0Halo** [comment]
Don't have rights to commit directly to master. Simply an update of package.json and package-lock.json to update from 0.0.1-alpha.19 to 0.0.1-alpha.20

**Review by sharkparty — CHANGES_REQUESTED** [review]
polished version bump plz

**Review by sharkparty — APPROVED** [review]
LGTM

**Comment by brandonlilly** [comment]
:+1:

**Comment by shaundub** [comment]
Bumping as part of bugfix for grid icon. Closing this PR.

**Pull request closed without merging**
