### PR TITLE
Add tag-add icon & check-circle

### PR DESCRIPTION
**Pull request by hannahmshin**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/retailmenot/anchor) and create your branch from `master`.
1. Run `npm i` in the repository root.
1. If you've fixed a bug or added code that should be tested, add tests!
1. Ensure the test suite passes (`npm run test`).
1. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run pretty`).
1. Make sure your code lints (`npm run lint`).

### CODE REVIEW

**Comment by hannahmshin** [comment]
i think that master branch snapshots are failing. due to weird styled-component hashes maybe?

```

    - Snapshot
    + Received

    @@ -1,7 +1,7 @@
      <div
    -   className="sc-bdVaJa doNtdz"
    +   className="sc-bdVaJa ePlbQy"
```

**Comment by andystalick** [comment]
As I understand our charter for Anchor, the idea is to build a set of UI primitives that a company like ours could then extend privately for our own use-case (like coupons)
In this instance, I'm not sure a tag icon would fall under the generic use-case. Likely we would want to make this modification as part of using the primitive in our internal work.

**Comment by sharkparty** [comment]
I’ll review this and provide some feedback. I can see a case either way, but I’ll ping @hannahmkim to understand this better. Sorry to be tardy—lots going on. =)

**Comment by sharkparty** [comment]
Alright, I think I understand this a bit better now. The icon we're contributing may have a unique usage at RMN, but it's definitely an icon that exists—though in other forms—in [common libraries](https://fontawesome.com/icons/tag?style=light), so I'd like to land this in Anchor as well as a few other icons. I did get a chance to brief @hannahmkim that our iconography is in a bit of a between state as designers are working to get alignment on their iconography, but in the meantime this icon seems to fit in well for this project.

**Review by sharkparty — APPROVED** [review]

**Pull request merged**
